### ISSUE TITLE
Issue while creating list

### ISSUE THREAD

**Issue by udaikumar26** [Redpill-Linpro/alfresco-listmanager#10]
Not able to add a new list throws error.
Below error is found in javascript console.
![list](https://user-images.githubusercontent.com/36712365/36811913-14d6c7e8-1c95-11e8-94b0-ed27f9ca3956.png)

Javascript error:
![list1](https://user-images.githubusercontent.com/36712365/36812013-5f9786dc-1c95-11e8-87d2-f27a604b1d08.png)

**Comment by billerby** [comment]
Are you still having this error? Can't reproduce and suspecting its related to the jar-problems you had?

**Comment by udaikumar26** [comment]
The issue got fixed. the amp was put into amps_share folder. now resolved after moving it to amps folder
