### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by udaikumar26** [Redpill-Linpro/alfresco-listmanager#12]
Got the below exception when starting alfresco.

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'patch.migrateFromNameToTitlePatch' defined in class path resource [alfresco/module/listmanager-amp/context/service-context.xml]: Error setting property values; nested exception is org.springframework.beans.PropertyBatchUpdateException; nested PropertyAccessExceptions (1) are:
PropertyAccessException 1: org.springframework.beans.MethodInvocationException: Property 'targetSchema' threw exception; nested exception is java.lang.IllegalArgumentException: 'targetSchema' must be greater than 'fixesToSchema'.

Fixed it by randomly changing the value of fixesToSchema to 1(instead of {version.schema}). Is that correct?

**Comment by billerby** [comment]
Which version of Alfresco are you on? This may be due to that the schema version after Alfresco 5.0 has gone beyond 10000, so setting that property to 100000 in the contex-file will probably fix this.

**Comment by udaikumar26** [comment]
Alfresco 5.2. What is the fix and where we need to change?

**Comment by billerby** [comment]
Fixed in new release 1.5.4
