### ISSUE TITLE
Is there a way to restrict access to list manager to specific groups

### ISSUE THREAD

**Issue by udaikumar26** [Redpill-Linpro/alfresco-listmanager#14]
Now, anyone with administrator role can go and edit the list manager. Is it possible to restrict access only to specific groups?

**Comment by billerby** [comment]
No, and btw you should be extremely restrictive with giving out administrator permissions, those users will have the possibility to delete all files in the repository. That said it would probably been a good idea to handle the admin of the listmanager in a specific configuration site instead where we could give a group of users edit permissions. No time for that though. Feel free to code it and issue a pull request.
