### ISSUE TITLE
Admin user can see options but any user cannot see it

### ISSUE THREAD

**Issue by DancingFighterG** [Redpill-Linpro/alfresco-listmanager#7]
Hello, we are working to use this List Manager add-on to be able to update pull list in share. We implemented this add-on in DEV and worked fine. We tried to implement this is our TEST and QA environment and we are experience the issue that the list items show up when you login as a admin but when any other users tries to see the list items the pulldown is blink.

**Comment by billerby** [comment]
Ok, your users in the TEST and QA does probably not have read permission in the data dictionary. Try changing so all users have READ on data-dictionary/Lists folder and its children.

https://github.com/Redpill-Linpro/alfresco-listmanager/blob/master/listmanager-amp/src/main/amp/config/alfresco/templates/webscripts/listboxes/listboxvalues.get.desc.xml
