### ISSUE TITLE
should we put the amp file into amps folder or amps_share folder of alfresco installation

### ISSUE THREAD

**Issue by udaikumar26** [Redpill-Linpro/alfresco-listmanager#9]
should we put the amp file into amps folder or amps_share folder of alfresco installation? in other words, does it get installed into share.war or alfresco.war?

**Comment by udaikumar26** [comment]
Also where should the jar file be put? I put it under tomcat/shared/classes but the link does not appear in share UI.

**Comment by udaikumar26** [comment]
Can anyone reply for this? we are having trouble installing listmanager and there is no clear documentation of how to install this.

**Comment by billerby** [comment]
There is one repository part (amp) which should be installed with the alfresco-mmt.jar. The share part is just a jar-file which could be dropped into the shared/classes dir of your tomcat installation.
